<?php

namespace AppBundle\Repository;

/**
 * CitasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitasRepository extends \Doctrine\ORM\EntityRepository
{
}
