<?php

namespace AppBundle\Repository;

/**
 * JusticiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JusticiaRepository extends \Doctrine\ORM\EntityRepository
{
}
