<?php

namespace AppBundle\Repository;

/**
 * VillanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillanoRepository extends \Doctrine\ORM\EntityRepository
{
}
